### PR TITLE
Correctly handle unicode input strings

### LINKED ISSUE #15: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
When I send utf-8 data to server, the following error raised.

example query string: `first_name=%D8%B9%D9%84%DB%8C`

error:

```
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
Exception Location:	/usr/lib/python2.7/encodings/utf_8.py in decode, line 16
Python Version:	2.7.6


Traceback:
File "/path/to/myfiles/views.py" in set_personal_information
  13.         params = parser.parse(request.POST.urlencode())
File "/usr/local/lib/python2.7/dist-packages/querystring_parser/parser.py" in parse
  123.             val = val.decode(encoding)
File "/usr/lib/python2.7/encodings/utf_8.py" in decode
  16.     return codecs.utf_8_decode(input, errors, True)

```

### PR DESCRIPTION
**Pull request by paulmelnikow**
Resolves #15

This is an alternate to #16 that includes a test. See discussion at #15.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
@bernii Just checking in about this. Are you willing to merge it?

**Comment by bernii** [comment]
yeah! sorry for the delay - thanks so much!

**Comment by smmoosavi** [comment]
Thank

**Comment by ashl1** [comment]
It seems you haven't tested with Python3. It doesn't work with Python 3.3 and produces error mentioned in #22

**Pull request merged**
