### PR TITLE
RELEASE 1.2.4

### PR DESCRIPTION
**Pull request by paulmelnikow**

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi @bernii! I thought I had access to publish this but it looks like not. Would you mind adding me?

https://pypi.org/user/paulmelnikow/

**Comment by bernii** [comment]
@paulmelnikow you are now an owner :) thanks!

**Comment by paulmelnikow** [comment]
Thanks!

**Comment by hanyouqiang** [comment]
InmemoryUpliadedFile: 4.jpg (image/jpeg) This file is converted to a string type after using Django

**Pull request merged**
