### PR TITLE
build wheel

### PR DESCRIPTION
**Pull request by chrisantonellis**
followed guidelines on `pythonwheels.com` to build a wheel alongside the sdist as part of the `python setup.py` build process.

the command that should be called now is `python setup.py sdist bdist_wheel` and all artifacts in the `dist/` directory should be uploaded to pypi 👍👍👍

### CODE REVIEW

**Comment by chrisantonellis** [comment]
any interest in merging this? I created the following issue for tracking: https://github.com/bernii/querystring-parser/issues/39

**Comment by chrisantonellis** [comment]
thanks for checking this out @professorhaseeb

**Comment by paulmelnikow** [comment]
Thanks!

**Comment by chrisantonellis** [comment]
@paulmelnikow sorry to bother! is it possible to get the `hacktoberfest-accepted` label on this PR? hopefully is it counted retroactively! Thanks for accepting my contribution!

**Pull request merged**
